# Generated by Django 4.2.9 on 2024-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=100)),
                ('nome_do_participante', models.CharField(max_length=100)),
                ('dia_hora', models.DateTimeField()),
            ],
        ),
    ]
