# Generated by Django 5.0.1 on 2024-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_livros_ano_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa_imagem',
            field=models.URLField(max_length=1000),
        ),
    ]
